version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=domecho-adm
      - MONGO_INITDB_ROOT_PASSWORD=@Mmjk4Y8Yj8N